### ISSUE TITLE
On own installation, “Unable to request certificate from Lets Encrypt” error during deploy

### ISSUE THREAD

**Issue by aral** [staticland/staticland-api#15]
Getting this error when I try to deploy to my own Staticland server.

No immediately obvious errors / more information being logged. I feel this is an issue in my configuration settings for the Let’s Encrypt-related settings.

I’m not entirely sure where these should point to/their purpose:

```
    letsEncryptDir: '/home/staticland/letsencrypt',
    letsEncryptCommand: '/home/staticland/certbot-auto',
    letsEncryptChallengeDir: '/home/staticland/api/html',
```

Given that the account I’m using on my server is `ubuntu`, I currently have:

```
    letsEncryptDir: '/home/ubuntu/letsencrypt',
    letsEncryptCommand: '/home/ubuntu/certbot-auto',
    letsEncryptChallengeDir: '/home/ubuntu/staticland-api/html',
```

(1) Is an empty directory I made, assuming that Staticland will use it to store Let‘s Encrypt related files. <strike>Not sure if this should be the Let’s Encrypt folder that Let’s Encrypt was installed in (i.e., `/etc/letsencrypt`) – will try that next.</strike>

(2) I have certbot-auto at that path. This should be correct.

(3) This points to the html folder in my staticland-api installation. Assuming this, too, is correct.

**Comment by aral** [comment]
I just looked up the certbot-wrapper project and noticed the note: “We recommend Ubuntu 16.10.”

Since the installation instructions for staticland-api state Ubuntu 14.04, that’s what I’d gone with. I don’t know whether this is the issue. Going to update the server to Ubuntu 16.10…

(Messed up server update… nuked it… starting from scratch. Will report back progress on 16.10.)

**Comment by aral** [comment]
OK, narrowed it down. It’s a bug in ssl.js, where the vhost template has the `/.well-known` challenge location for Let’s Encrypt is hardcoded:

```
  location @error {
    root /home/staticland/staticland-api/html;
  }

  location ~ /.well-known {
    root /home/ubuntu/staticland-api/html;
  }
}`
}
```

(The error route is also hardcoded but that’s a separate issue.)

**Comment by aral** [comment]
More hard-coded `static.land` domain references in site.js:

```
Site.prototype.firstDeploy = function siteDeploy (opts, callback) {
  if (!opts) return callback(new Error('options object with domain and owners properties required'))
  if (!opts.domain) return callback(new Error('domain property required'))
  if (!opts.owners) return callback(new Error('owners property required'))
  var self = this

  var isSubdomain = opts.domain.indexOf('static.land') > -1
  var matchesReserved = this.reserved.indexOf(opts.domain.split('.static.land')[0]) > -1

  if (isSubdomain && matchesReserved) {
    return callback(new Error('subdomain ' + opts.domain + ' not available'))
  }
```

**Comment by aral** [comment]
OK, so what’s failing is the nginx reload. Can recreate form the command-line: 

```
ubuntu@staticland:~/staticland.ind.ie$ sudo nginx -s reload
nginx: [emerg] BIO_new_file("/home/ubuntu/letsencrypt/config/live/cyborgrights.eu/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/ubuntu/letsencrypt/config/live/cyborgrights.eu/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```

So the cert isn’t created by the time Staticland tries to reload nginx.

Diving back into the source code…

**Comment by aral** [comment]
Right, I think I’ve narrowed it down: 

in cert.js: 

` if (config.requestCerts === false) return callback()`

is `false` (and thus returning `callback()`) even in production mode (`NODE_ENV="production"` is exported) and even though the config.js has:

```
  production: {
    secret: process.env.STATICLAND_SECRET,
    requestCerts: true,
    debug: true
  }
```

**Comment by aral** [comment]
OK, so `export NODE_ENV=production` isn’t picked up by forever if you start the app with `forever start index.js`

However, if you specify it in the command itself, it is:

```
NODE_ENV=production forever start index.js
```

(This should be updated in the docs. TODO: issue/PR)

Now I have another issue: getting a bad request back from Let’s Encrypt. Well, I guess it’s progress… :)

**Comment by aral** [comment]
Also, you need to specify an email field in config.js for your email address to be used for the Let’s Encrypt cert.

**Comment by aral** [comment]
OK, so the correct certbot command (cmd) isn’t being passed to the certbot-wrapper. It defaults to `"certbot"` (which doesn’t exist, so the exec is failing) instead of passing the actual path (e.g.) `"/home/ubuntu/certbot-auto"`

Now Let’s Encrypt is being run but that’s returning error… another step forward…

**Comment by aral** [comment]
OK, the Let’s Encrypt issue is from my not updating the IP address in the A-record when I recreated the server from scratch this morning on 16.10.

**Comment by aral** [comment]
OK, now the Let’s Encrypt cert is being created correctly but the site hasn’t been uploaded.

**Comment by sethvincent** [comment]
Hey @aral! Thanks for opening this and for all the notes as you've been debugging.

You might be the first person other than me to set up an instance, so I apologize if things are a little messy.

I'm busy right now but I'll look at this (and your PR and issues on the cli repo) in depth later today.

**Comment by aral** [comment]
Hey @sethvincent, no worries + thanks so much for sharing Staticland – it’s going to be *awesome* once I have it running… I’m *almost* there… now stuck trying to understand how to debug why the site contents (sent over via the `tarstream`) are not being written out to `/sites/html/<sitename>/` – I can see the stream being created on the client and `unpackTarball()` is completing but the `unpackTarball` callback is not getting called in the `deploy` function in `/lib/handlers/sites.js` (I should probably get some sleep and look into it tomorrow – any tips you might have gladly accepted) :) 

PS. I know how it is – I tried to make the third-party install of Better (https://source.ind.ie/better) as simple as possible with automated scripts, etc., and still the first person to try to install the whole thing had quite a few issues. It’s just how it goes… hopefully we can streamline it based on this experience + the notes here, etc. Thanks again for making this and sharing it – very, very cool :)

**Comment by sethvincent** [comment]
That's strange. Are the files being created in `/sites/html/<sitename>/`?

My first guess is a permissions issue, but that might not be it.

**Comment by aral** [comment]
Nope, no files in that directory. Will continue trying to debug it today and report back when I have something.

PS. Permissions seem fine: 
`drwxrwxr-x  3 ubuntu ubuntu 4096 May 19 12:07 html`

**Comment by aral** [comment]
Could this be related to https://github.com/request/request/issues/2499 ?

**Comment by aral** [comment]
Basically, I’ve narrowed this down to a hang between the client and server as the tarstream is being piped until a timeout.

The tar-fs tarstream object created on the client –– can you see anything wrong with this @sethvincent  (does anything jump out at you immediately, by chance, @mafintosh?)

```
Pack {
  _readableState:
   ReadableState {
     objectMode: false,
     highWaterMark: 16384,
     buffer: BufferList { head: null, tail: null, length: 0 },
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: null,
     ended: false,
     endEmitted: false,
     reading: false,
     sync: true,
     needReadable: false,
     emittedReadable: false,
     readableListening: false,
     resumeScheduled: false,
     defaultEncoding: 'utf8',
     ranOut: false,
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: true,
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  _drain: [Function: noop],
  _finalized: false,
  _finalizing: false,
  _destroyed: false,
  _stream: null }
```

**Comment by sethvincent** [comment]
I'm realizing there should probably be `req.on('error', cb)` and `tarstream.on('error', cb)` listeners in https://github.com/staticland/staticland-api/blob/master/lib/unpack-tarball.js. There might be an error we're not catching?

**Comment by aral** [comment]
Oddly,` tarstream.on('finish'…)` is getting called properly (and `on('error'…)` isn't getting called there or on `req` – just tried adding the handlers to both).

`req.on('end', callback)` isn’t getting called.

May I cry now? :)

**Comment by aral** [comment]
I also added a map function to the see if the files were being untarred and it’s *not* getting called. (Although the mapStream version on the client *is* – so I know the files are being tarred.)

```
      var tarstream = tar.extract(htmlpath, {
        dmode: octal(555),
        fmode: octal(444),
        map: function(header){
          console.log("Extracting: " + path.basename(header.name));
          return header
        }
      })
```

**Comment by aral** [comment]
Possibly related? 

* <strike>req.on('end') not getting called for streams: https://github.com/nodejs/node/issues/2156</strike> End is not getting called as the pipe seems to be hanging. Can pipes hang? I’m going to go get a drink now…
* <strike>`bodyParser` getting in the way: http://stackoverflow.com/questions/18728039/express-req-pipe-does-not-work</strike> (Not being used; was confused by another dependency mentioning it. `req.body` is `undefined` at time of `req.pipe()` statement.)

**Comment by aral** [comment]
Just an update: I’ve failed to resolve the hanging stream issue. Unfortunately do not have time to devote to debugging this further at the moment. Going to look for another solution in the interim.

**Comment by aral** [comment]
Right, giving it another shot – @sethvincent, can you please let me know what version of Node is running on your server?

**Comment by aral** [comment]
Well, ~42 days of off-and-on trying later I finally got it working.

How?

The culprit was – *drumroll* – npm and semver. Something in one of the packages was messing things up silently.

The fix: I removed all minor version matches in `package.json` (`^`), replacing them with the actually specified versions. And voila, it works.

Yay!

PS. Yes, you can take this as a public service announcement to use a deterministic package manager like [yarn](https://yarnpkg.com/lang/en/) instead.

**Comment by modulitos** [comment]
@aral Yikes - this sounds like a nasty bug! But thanks for sharing your findings :-)

FYI, with node 8.x and npm 5.x, you should have deterministic packaging, similar to what yarn provides (and [nvm](https://github.com/creationix/nvm/blob/master/README.md) is a great tool for managing node versions). For example, with npm 5.x, running `npm install` should produce a `package-lock.json` file, which is similar to the `yarn.lock` file. If that works for you, it would be great if you can commit that file to help future users from encountering this bug :-)

More info on npm 5:
http://blog.npmjs.org/post/161081169345/v500
http://blog.scottlogic.com/2017/06/06/does-npm5-deprecate-yarn.html

and adding the `package-lock.json` file:
https://stackoverflow.com/questions/44552348/should-i-commit-yarn-lock-and-package-lock-json-files
